### PR TITLE
docs: replaces pg-format with node-pg-format

### PR DESCRIPTION
**Pull request by moltar**

### CODE REVIEW

**Comment by moltar** [comment]
Thanks for the fork and the rewrite to TS!

~~Saved my @$$ from a runtime require issue in bundled code :)~~

~~https://github.com/datalanche/node-pg-format/blob/3157b520bfec69b05c20f578537c0fe8861f6edf/lib/index.js#L4~~

Scratch that. This module suffers from the same issue 😂 

Why do we need the runtime require? Why can't it just be an import?

**Comment by moltar** [comment]
I've created my own package based on yours, but I fixed most of the TS issues and also importing keywords.

https://github.com/ScaleLeap/pg-format

**Comment by cphillips** [comment]
> I've created my own package based on yours, but I fixed most of the TS issues and also importing keywords.
> 
> https://github.com/ScaleLeap/pg-format

Just checked it out, nice work

**Comment by cphillips** [comment]
Version 1.3.5 negates the need for this PR

**Pull request closed without merging**
